version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16

    steps:
      - checkout

      # Automate Android SDK Setup
      - run:
          name: Automate Android SDK Setup
          command: |
            echo 'export ANDROID_HOME=/opt/android' >> $BASH_ENV
            echo 'export PATH="$ANDROID_HOME/tools:$PATH:$ANDROID_HOME/platform-tools"' >> $BASH_ENV
            source $BASH_ENV
            if [ ! -f android/local.properties ]; then
              echo 'sdk.dir=/opt/android' > android/local.properties
              echo 'Local properties file created. SDK location set to /opt/android.' >&2
            fi

      # # Check if native_modules.gradle file exists, if not, create it
      - run:
          name: Check and Create native_modules.gradle
          command: |
            if [ ! -f node_modules/@react-native-community/cli-platform-android/native_modules.gradle ]; then
              echo 'File not found. Creating native_modules.gradle...'
              mkdir -p node_modules/@react-native-community/cli-platform-android
              echo '// This file is intentionally left blank.' > node_modules/@react-native-community/cli-platform-android/native_modules.gradle
            else
              echo 'native_modules.gradle file found.'
            fi

      # Remaining steps...
      - run:
          name: Check Node.js Version
          command: node -v

      - run:
          name: Clear npm Cache
          command: npm cache clean --force

      - run:
          name: Install Java
          command: |
            sudo apt-get update
            sudo apt-get install default-jdk -y
            echo 'export JAVA_HOME=/usr/lib/jvm/default-java' >> $BASH_ENV
            echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      # Rest of the steps...
      - run:
          name: Build APK
          command: |
            cd android
            chmod +x gradlew
            ./gradlew assembleRelease

      - store_artifacts:
          path: android/app/build/outputs/apk/release/
          destination: release-apk/

workflows:
  version: 2
  build:
    jobs:
      - build
