version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    environment:
      JAVA_HOME: /usr/bin/java  # Replace this with the path you've set
    steps:
      - checkout
      - run:
          name: Check Node.js Version
          command: node -v
      - run:
          name: Clear npm Cache
          command: npm cache clean --force
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install --verbose
            npm install react-native --verbose
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build APK
          command: |
            cd android
            chmod +x gradlew
            ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release/
          destination: release-apk/

workflows:
  version: 2
  build:
    jobs:
      - build
