version: 2.1

workflows:
  build-and-test:  # Name of the workflow

    jobs:
      - build-android-app  # Job name

jobs:
  build-android-app:
    docker:
      - image: circleci/android:api-33

    steps:
      - checkout

      # Install dependencies (if not using Orb)
      # - run: npm install

      # Build the APK (using Orb - recommended)
      - react-native/android_build:
          path: ./android  # Path to your Android project directory

      # Build the APK (without Orb)
      # - run: cd android && ./gradlew assembleRelease
