version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16

    steps:
      - checkout

      # Set Android SDK Location
      - run:
          name: Set Android SDK Location
          command: |
            echo 'export ANDROID_HOME=/opt/android' >> $BASH_ENV
            echo 'export PATH="$ANDROID_HOME/tools:$PATH:$ANDROID_HOME/platform-tools"' >> $BASH_ENV
            source $BASH_ENV

      # Check Node.js Version
      - run:
          name: Check Node.js Version
          command: node -v

      # Clear npm Cache
      - run:
          name: Clear npm Cache
          command: npm cache clean --force

      # Install Java
      - run:
          name: Install Java
          command: |
            sudo apt-get update
            sudo apt-get install default-jdk -y
            echo 'export JAVA_HOME=/usr/lib/jvm/default-java' >> $BASH_ENV
            echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      # Restore npm dependencies cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      # Install Node.js dependencies
      - run:
          name: Install Dependencies
          command: |
            npm install --verbose
            npm install react-native --verbose

      # Save npm dependencies cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Set local.properties file
      - run:
          name: Set local.properties
          command: |
            echo 'sdk.dir=/opt/android' > android/local.properties

      # Build APK
      - run:
          name: Build APK
          command: |
            cd android
            chmod +x gradlew
            ./gradlew assembleRelease

      # Store generated APK as an artifact
      - store_artifacts:
          path: android/app/build/outputs/apk/release/
          destination: release-apk/

workflows:
  version: 2
  build:
    jobs:
      - build
