version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
   
    steps:
      - checkout
        - run:
          name: Install Java
          command: |
            brew tap AdoptOpenJDK/openjdk
            brew install --cask adoptopenjdk17
            echo 'export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-17.jdk/Contents/Home"' >> $BASH_ENV
            echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Check Node.js Version
          command: node -v
      - run:
          name: Clear npm Cache
          command: npm cache clean --force
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install --verbose
            npm install react-native --verbose
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build APK
          command: |
            cd android
            chmod +x gradlew
            ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release/
          destination: release-apk/

workflows:
  version: 2
  build:
    jobs:
      - build
