version: 2.1

jobs:
  build:
    macos:
      xcode: latest
    steps:
      - checkout

      - run:
          name: Install Java
          command: |
            brew tap AdoptOpenJDK/openjdk
            brew install --cask adoptopenjdk17
            echo 'export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-17.jdk/Contents/Home"' >> $BASH_ENV
            echo 'export PATH="$JAVA_HOME/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Validate Gradle wrapper
          command: ./gradlew --version

      - run:
          name: Setup Node.js
          command: |
            brew install node@18
            echo 'export PATH="/usr/local/opt/node@18/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install Yarn and dependencies
          command: |
            npm install -g corepack
            yarn install

      - run:
          name: Build application
          command: |
            cd android
            ./gradlew assembleRelease

      - persist_to_workspace:
          root: android/app/build/outputs/apk/release
          paths:
            - app-release.apk

workflows:
  version: 2
  build:
    jobs:
      - build
